logging:
  level:
    at.ac.tuwien.sepm.assignment.individual: TRACE
    root: INFO
  file:
    name: ./log/wendys-friends.log
spring:
  application:
    name: wendys-family-tree
  datasource:
    url: "jdbc:h2:./wendydb;AUTO_SERVER=TRUE;INIT=RUNSCRIPT FROM 'classpath:sql/createSchema.sql'"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
server:
  port: 8080
  error:
    include-message: always
